package com.sbz.dsp

import com.sbz.dsp.model.DspConfig

/**
 * Realtime bridge from sBz's 32-band parametric EQ to Android
 * DynamicsProcessing.
 *
 * The EQ resolution is deliberately fixed at 32 bands.  The 32 logical
 * frequencies are also the 32 physical DP cutoffs, so a realtime fader move
 * never creates a 127/128-band staircase, never runs an FFT-bin fit and never
 * moves the physical layout.
 *
 * The response itself is still generated by the Equalizer314-style
 * ParametricEqualizer/BiquadFilter RBJ model.  For each fixed DP band we sample
 * the complete parametric response at that band's frequency and write the
 * resulting gain to DynamicsProcessing.
 */
object ParametricToDpConverter {

    private const val BAND_COUNT = 32
    private const val MIN_FREQ = 20f
    private const val MAX_FREQ = 22000f

    /** Optional shared EQ layer. Its response is added to the active curve. */
    @Volatile
    var overlayEq: ParametricEqualizer? = null

    data class ConvertedBands(
        val cutoffs: FloatArray,
        val gains: FloatArray,
    )

    private fun respond(eq: ParametricEqualizer, frequencyHz: Float): Float {
        val base = eq.getFrequencyResponse(frequencyHz)
        val overlay = overlayEq
        return if (overlay != null && overlay !== eq) {
            base + overlay.getFrequencyResponse(frequencyHz)
        } else {
            base
        }
    }

    /**
     * Fast fixed-layout conversion for the sBz EQ32 realtime path.
     *
     * Complexity is 32 fixed response samples instead of an FFT/grid
     * deconvolution. The cutoff positions never change while the user moves a
     * fader.
     */
    fun convertFixed32(
        eq: ParametricEqualizer,
        frequenciesHz: FloatArray = DspConfig.FREQUENCIES,
    ): ConvertedBands {
        require(frequenciesHz.size == BAND_COUNT) {
            "sBz realtime EQ requires exactly $BAND_COUNT bands"
        }

        val cutoffs = FloatArray(BAND_COUNT)
        val gains = FloatArray(BAND_COUNT)

        var previous = MIN_FREQ
        for (i in 0 until BAND_COUNT) {
            var cutoff = frequenciesHz[i].coerceIn(MIN_FREQ, MAX_FREQ)
            if (i > 0 && cutoff <= previous) {
                cutoff = (previous + 0.001f).coerceAtMost(MAX_FREQ)
            }

            cutoffs[i] = cutoff
            gains[i] = respond(eq, cutoff)
            previous = cutoff
        }

        return ConvertedBands(cutoffs, gains)
    }
}
